POST http://localhost:4004/odata/v4/myservice/leave HTTP/1.1
Content-Type: application/json

{
    "emp_id_ID":"12345",
    "emp_name_ID":"veeneth",
    "emp_mail_ID":"maroon@gmil.com",
    "start_date":"2026-02-05",
    "end_date":"2026-02-06",
    "type":"marriage",
    "status_code":"SL"
}
###
DELETE http://localhost:4004/odata/v4/myservice/employees(ID='e7b3d9f1-2a6c-4e58-8f10-5c9a2d4b1e76') HTTP/1.1

###
POST http://localhost:4004/odata/v4/myservice/leave   HTTP/1.1
Content-Type: application/json

{
    "emp_id_ID":"4b7e9a2c-6d5f-4a13-8c20-1f9e3d5b7a65",
    "employee_name_ID":"john_doe",
    "start_date":"2026-03-10",
    "end_date":"2026-03-12",
    "type":"Marriage",
    "status_code":"SL"
    
}

###
PATCH http://localhost:4004/odata/v4/myservice/Attendance(ID='7a2e4f6b-1c9d-4a88-bf21-0e6d2c9a7f36') HTTP/1.1
Content-Type: application/json

{
    "hours":6,
    "status_code":"WFH"
}

###
GET http://localhost:4004/odata/v4/myservice/leave HTTP/1.1

###
GET http://localhost:4004/odata/v4/myservice/Attendance?$filter=status eq 'present' HTTP/1.1

###
GET http://localhost:4004/odata/v4/myservice/AttendanceStatus HTTP/1.1


###
POST http://localhost:4004/odata/v4/myservice/Attendance  HTTP/1.1
Content-Type: application/json

{
    "emp_id_ID":"bbin58",
    "emp_name_ID":"mithun",
    "emp_mail_ID":"mithun@bb.com",
    "Date":"2026-01-23",
    "status_code":"WFH",
    "hours":8.0
}
###

DELETE http://localhost:4004/odata/v4/myservice/leave(ID='cd0bb1ad-96c7-4902-9647-7656609d9112') HTTP/1.1
###
DELETE http://localhost:4004/odata/v4/myservice/leave(ID='45ddde73-ce79-4eec-b371-e7a860cbf1f6') HTTP/1.1
###
DELETE http://localhost:4004/odata/v4/myservice/leave(ID='cf53fe8e-17f4-4429-b0af-3bdb68437c18') HTTP/1.1
###
PATCH http://localhost:4004/odata/v4/myservice/employees(ID='e7b3d9f1-2a6c-4e58-8f10-5c9a2d4b1e75') HTTP/1.1
Content-Type: application/json

{
    "emp_name":"marron"
}




